/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package suwakaplikacjatestująca;

/**
 *
 * @author Sebastian
 */
public class SuwakAplikacjaTestująca extends javax.swing.JFrame {

    /**
     * Creates new form SuwakAplikacjaTestująca
     */
    public SuwakAplikacjaTestująca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        slider1 = new suwakkomponent.Slider();
        jLabel2 = new javax.swing.JLabel();
        wartosc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        minimum = new javax.swing.JTextField();
        maksimum = new javax.swing.JTextField();
        UstawWartosci = new javax.swing.JButton();
        Kolory = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Glowki = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Rotate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        slider1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slider1MouseClicked(evt);
            }
        });
        slider1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                slider1MouseDragged(evt);
            }
        });

        jLabel2.setText("wartość:");

        jLabel1.setText("wartość minimalna");

        jLabel3.setText("wartość maksymalna");

        minimum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                minimumKeyReleased(evt);
            }
        });

        maksimum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                maksimumKeyReleased(evt);
            }
        });

        UstawWartosci.setText("Ustaw");
        UstawWartosci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UstawWartosciActionPerformed(evt);
            }
        });

        Kolory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "czarny", "czerwony", "niebieski", "różowy" }));
        Kolory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KoloryActionPerformed(evt);
            }
        });

        jLabel4.setText("Kolor Slidera");

        jLabel5.setText("Rodzaj główki");

        Glowki.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "prostokat", "trojkat", "kolo" }));
        Glowki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GlowkiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(slider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(maksimum, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(minimum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UstawWartosci)
                .addGap(131, 131, 131)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(Kolory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Glowki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wartosc)
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(slider1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(wartosc)
                                    .addComponent(Kolory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Glowki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(minimum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(maksimum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(UstawWartosci)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton1)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        slider1.Rotate();
        slider1.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void slider1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slider1MouseClicked
        // TODO add your handling code here:
        slider1.setSzer(evt.getX());
        slider1.setWys(evt.getY());
        slider1.repaint();
        slider1.setWartosc(0);
        wartosc.setText(String.valueOf(slider1.getWartosc()));
    }//GEN-LAST:event_slider1MouseClicked

    private void slider1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slider1MouseDragged
        // TODO add your handling code here:
        slider1.setSzer(evt.getX());
        slider1.setWys(evt.getY());
        slider1.repaint();
        slider1.setWartosc(0);
        wartosc.setText(String.valueOf(slider1.getWartosc()));
    }//GEN-LAST:event_slider1MouseDragged

    private void minimumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_minimumKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
           
            } else {
               minimum.setText("");
            }
    }//GEN-LAST:event_minimumKeyReleased

    private void maksimumKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maksimumKeyReleased
        // TODO add your handling code here:
            if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
           
            } else {
               maksimum.setText("");
            }
    }//GEN-LAST:event_maksimumKeyReleased

    private void UstawWartosciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UstawWartosciActionPerformed
        // TODO add your handling code here:
        if(Integer.parseInt(maksimum.getText()) > Integer.parseInt(minimum.getText())){
        slider1.setMaksimum(maksimum.getText());
        slider1.setMinimum(minimum.getText());
        }else{
        slider1.setMaksimum(minimum.getText());
        slider1.setMinimum(maksimum.getText());
        }
        
        slider1.repaint();
        slider1.setWartosc(0);
        wartosc.setText(String.valueOf(slider1.getWartosc()));
    }//GEN-LAST:event_UstawWartosciActionPerformed

    private void KoloryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KoloryActionPerformed
        // TODO add your handling code here:
        slider1.setKolor(Kolory.getSelectedItem().toString());
        slider1.repaint();
    }//GEN-LAST:event_KoloryActionPerformed

    private void GlowkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GlowkiActionPerformed
        // TODO add your handling code here:
        slider1.setGlowka(Glowki.getSelectedIndex()+1);
        slider1.repaint();
    }//GEN-LAST:event_GlowkiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuwakAplikacjaTestująca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuwakAplikacjaTestująca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuwakAplikacjaTestująca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuwakAplikacjaTestująca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuwakAplikacjaTestująca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Glowki;
    private javax.swing.JComboBox<String> Kolory;
    private javax.swing.JButton UstawWartosci;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField maksimum;
    private javax.swing.JTextField minimum;
    private suwakkomponent.Slider slider1;
    private javax.swing.JLabel wartosc;
    // End of variables declaration//GEN-END:variables
}
